In [13]:
import cv2
import numpy as np


cap=cv2.VideoCapture(0);
faceClassif=cv2.CascadeClassifier("haarcascade_eye.xml")

while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    faces=faceClassif.detectMultiScale(gray,
                                       scaleFactor=1.3,
                                       minNeighbors=10,
                                       minSize=(30,30),
                                       maxSize=(300,300))
    print(type(faces))
    print(faces)
    print(len(faces))
    if len(faces)==1:
        for (x,y,w,h) in faces:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
            texto="ROSTRO DETECTADO DETECTADO"
            cv2.putText(frame,text=texto ,org=(0,50), fontFace=cv2.FONT_HERSHEY_COMPLEX, fontScale=1,color=(0,0,0), thickness=2)

    cv2.imshow('frame',frame)

    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[315 116  48  48]]
1
<class 'numpy.ndarray'>
[[411 102  53  53]
 [315 115  50  50]]
2
<class 'numpy.ndarray'>
[[410 106  48  48]
 [315 119  44  44]]
2
<class 'numpy.ndarray'>
[[410 106  48  48]
 [315 119  44  44]]
2
<class 'numpy.ndarray'>
[[406 106  50  50]
 [315 118  46  46]]
2
<class 'numpy.ndarray'>
[[406 106  50  50]
 [315 118  46  46]]
2
<class 'numpy.ndarray'>
[[411 105  49  49]
 [315 117  47  47]]
2
<class 'numpy.ndarray'>
[[411 105  49  49]
 [315 117  47  47]]
2
<class 'numpy.ndarray'>
[[413 108  45  45]
 [316 116  49  49]]
2
<class 'numpy.ndarray'>
[[413 108  45  45]
 [316 116  49  49]]
2
<class 'numpy.ndarray'>
[[413 103  50  50]
 [314 115  50  50]]
2
<class 'numpy.ndarray'>
[[413 103  50  50]
 [314 115  50  50]]
2
<class 'numpy.ndarray'>
[[410 100  53  53]
 [313 111  54  54]]
2
<class 'numpy.ndarray'>
[[405 101  53  53]
 [314 115  49  49]]
2
<class 'numpy.ndarray'>
[[405 101  53  53]
 [314 115  49  49]]
2
<class 'numpy.ndarray'>
[[411 102  52  52]
 

In [15]:
import tkinter as tk
from PIL import Image, ImageTk
import cv2
from datetime import datetime
from tkinter.messagebox import showinfo

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.width, self.height = 600, 400
        self.title("Photo Kiosk")
        self.resizable(0, 0)
        self.faceClassif=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")


        self.protocol("WM_DELETE_WINDOW", self.quit)

        self.cap = cv2.VideoCapture(0)

        frm1 = tk.LabelFrame(self, text="Image Preview")
        frm2 = tk.Frame(self)
        frm1.pack(padx=10, pady=10)
        frm2.pack(padx=10, pady=10)

        self.canvas = tk.Canvas(frm1, width=self.width, height=self.height, borderwidth=1, relief='sunken')
        self.canvas.pack()

        self.btnTakePic = tk.Button(frm2, text="Take Pic!", width=24, font="Arial 12 bold", command=self.take_pic)
        self.btnTakePic.pack(padx=5, pady=5)

        self.update_image()


    def update_image(self):

        ret, frame = self.cap.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = cv2.resize(frame, (self.width, self.height))
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        self.faces=self.faceClassif.detectMultiScale(gray,
                                       scaleFactor=1.3,
                                       minNeighbors=5,
                                       minSize=(30,30),
                                       maxSize=(300,300))
        for (x,y,w,h) in self.faces:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),2)
            texto="ROSTRO DETECTADO DETECTADO"
            cv2.putText(frame,text=texto ,org=(0,50), fontFace=cv2.FONT_HERSHEY_COMPLEX, fontScale=1,color=(0,0,0), thickness=2)


        try:
            photo = ImageTk.PhotoImage(image=Image.fromarray(frame))
            self.canvas.create_image(0, 0, image=photo, anchor='nw')
            self.canvas.image = photo
        except:
            pass

        self.after(100, self.update_image)


    def take_pic(self):
        ret, frame = self.cap.read()
        filename = f"C:\\Users\\Cristian\\OneDrive - Universidad Peruana de Ciencias\\UPC-VII\\PROGRA_AVA_COMP\\{datetime.now():'%d%m%Y_%H_%M'}.jpg"
        cv2.imwrite(filename, frame)
        showinfo("Picture Saved", f"Se guardo una captura de la imagen en {filename}")


    def quit(self):
        if self.cap.isOpened():
            self.cap.release()
        self.destroy()


app = App().mainloop()

In [3]:
#autor: Cruz Asencios, Cristian Elvis

import tkinter as tk
from PIL import Image, ImageTk
import cv2
from datetime import datetime
from tkinter.messagebox import showinfo
import time


class App(tk.Tk):
    def __init__(self):

        super().__init__()
        self.width, self.height = 600, 400
        self.geometry("600x460+100+100")
        self.title("Photo Kiosk")
        self.resizable(0, 0)

        self.protocol("WM_DELETE_WINDOW", self.quit)
        self.faces = []
        self.eyes = []
        self.con = 0 #no se para que sirve esto
        self.condition=True
        self.unicavez=True

        #haarcascade
        self.face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
        self.eyes_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_eye.xml")
        self.cap = cv2.VideoCapture(0)

        frm1 = tk.LabelFrame(self, text="Image Preview")
        frm1.pack(padx=10, pady=10)
        #camvas
        self.canvas = tk.Canvas(frm1, width=self.width, height=self.height, borderwidth=1, relief='sunken')
        self.canvas.pack()

        #statusbar
        self.statusbar = tk.Label(self, text="Listo…", bd=1, relief=tk.SUNKEN, anchor=tk.W)
        self.statusbar.pack(side=tk.BOTTOM, fill=tk.X)
        self.update_image()
    #definición del método update_image-no recibe parámetros



    def update_image(self):


        if self.unicavez==True:#solo para inicializar la variable el objeto.fotoCap
            ret, frame = self.cap.read()
            _, x_win_pos, y_win_pos = self.geometry().split("+")
            self.fotoCap=Details_Photo(x_win_pos, y_win_pos, frame)
            self.fotoCap.quit2()
            self.unicavez=False


        ret, self.frame = self.cap.read()
        self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
        self.frame = cv2.resize(self.frame, (self.width, self.height))
        self.gray = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)

        self.faces = self.face_cascade.detectMultiScale(self.gray, scaleFactor=1.3,
                                       minNeighbors=5,
                                       minSize=(20,20),
                                       maxSize=(300,300))

        ###############################################################################
        for (fx, fy, fw, fh) in self.faces:
            cv2.rectangle(self.frame, (fx, fy-20), (fx + fw, fy ), (0,255,0), thickness=-2)
            cv2.putText(self.frame, org=(fx+25,fy-5),text="SUJETO DETECTADO", fontFace=cv2.FONT_HERSHEY_DUPLEX ,fontScale=0.5,color=(0,0,0),thickness=2)
            cv2.rectangle(self.frame, (fx, fy), (fx + fw, fy + fh), (0,255,0), thickness=2)
            #roi: para que la detección de rostro se lleve a cabo dentro del cuadrado
            roi_gray = self.gray[fy:fy + fh - 80, fx:fx + fw]
            roi_color = self.frame[fy:fy + fh, fx:fx + fw]

            self.eyes = self.eyes_cascade.detectMultiScale(roi_gray,scaleFactor=1.3,
                                       minNeighbors=5,
                                       minSize=(10,10),
                                       maxSize=(400,400))
            for (ex, ey, ew, eh) in self.eyes:
                cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 255), 2)
        ##################################################################################

        if (len(self.eyes) == 1):
            self.cont = self.cont + 1#se implemeta un contador para evitar falsos positivos
            if self.cont == 5:
                self.cont = 0
                #self.save_delete_photo()
                ##___________________________________________
                if self.condition==True:
                    self.statusbar.config(text='Imagen Capturada')

                    ret, frame = self.cap.read()
                    _, x_win_pos, y_win_pos = self.geometry().split("+")
                    self.fotoCap= Details_Photo(x_win_pos, y_win_pos, frame)
                    print("Esto es una captura")
                    self.condition=False
                else:
                    pass
                #________________________________
                #print(self.photo.flag_control())
        else:
            self.cont = 0


        try:
            photo = ImageTk.PhotoImage(image=Image.fromarray(self.frame))
            self.canvas.create_image(0, 0, image=photo, anchor='nw')

            self.canvas.image = photo
        except:
            pass

        #Este mensaje se muestra en el statusbar si es que se detecta el rostro de la persona
        if len(self.faces) == 1:
            self.statusbar.config(text='Rostro detectado')
        else:
            self.statusbar.config(text='Detectanto Rostro')

        self.condition=self.fotoCap.flag_control()
        #rint(self.condition)
        self.after(100, self.update_image)
    def save_delete_photo(self):
        #time.sleep(3)
        pass

    def quit(self):
        if self.cap.isOpened():
            self.cap.release()
        self.destroy()


class Details_Photo(tk.Toplevel):
    def __init__(self, x_win_pos, y_win_pos, frame,):

        super().__init__()
        self.title("Details Window")
        self.geometry(f"700x500+{int(x_win_pos) + 100}+{int(y_win_pos) + 100}")
        self.protocol("WM_DELETE_WINDOW", self.quit2)
        self.grab_set()
        self.focus()
        self.condicion=False
        self.frame = frame
        self.width, self.height = 600, 400
        frm1 = tk.LabelFrame(self, text="Image Preview")
        frm2 = tk.Frame(self)
        frm1.pack(padx=10, pady=10)
        frm2.pack(padx=10, pady=10)

        self.canvas = tk.Canvas(frm1, width=self.width, height=self.height, borderwidth=1, relief='sunken')
        self.canvas.pack()

        self.Guardar = tk.Button(frm2, text="Guardar", width=16, command=self.guardar_photo)
        self.descartar = tk.Button(frm2, text="Descartar", width=16, command=self.descartar_photo)
        self.Guardar.grid(row=0, column=0, padx=10, pady=10)
        self.descartar.grid(row=0, column=1, padx=10, pady=10)

        self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
        self.frame = cv2.resize(self.frame, (self.width, self.height))

        try:
            photo = ImageTk.PhotoImage(image=Image.fromarray(self.frame))
            self.canvas.create_image(0, 0, image=photo, anchor='nw')
            self.canvas.image = photo
        except:
            pass

    def guardar_photo(self):

        self.frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2RGB)
        self.frame = cv2.resize(self.frame, (self.width, self.height))
        filename = f"{datetime.now():'%d%m%Y_%H_%M'}.jpg"
        cv2.imwrite(filename, self.frame)
        showinfo("Picture Saved", f"Se guardo una captura de la imagen en {filename}")
        self.condicion=True
        self.destroy()

    def descartar_photo(self):
        self.condicion=True
        self.destroy()

    def flag_control(self):
        if self.condicion==True:
            return True
        else:
            return False

    def quit2(self):
        self.condicion=True
        self.destroy()

app = App().mainloop()



In [4]:
from tkinter.messagebox import showinfo, askokcancel, WARNING

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Menu")
        self.geometry("300x300+100+100")
        self.protocol("WM_DELETE_WINDOW", self.quit_app)

        frm = tk.Frame(self)
        frm.pack(padx=10, pady=10)

        # Se define el menu principal y se le asigna el widget a la ventana self.master
        main_menu = tk.Menu(self)
        self.config(menu=main_menu)

        # Se definen los menus (submenus) del menu principal
        menu_archivo = tk.Menu(main_menu, tearoff=False)
        menu_acerca_de = tk.Menu(main_menu, tearoff=False)

        # Se define la organizacion de los menus (command, separator, cascade)
        menu_archivo.add_command(label="Abrir")
        menu_archivo.add_separator()
        menu_archivo.add_command(label="Salir", command=self.quit_app)

        menu_acerca_de.add_command(label="Acerca de...", command=self.acerca_de)

        main_menu.add_cascade(label="Archivo", menu=menu_archivo)
        main_menu.add_cascade(label="Ayuda", menu=menu_acerca_de)


    def acerca_de(self):
        showinfo(title="Acerca de...", message="Tkinter App\nVer. 1.0")


    def quit_app(self):
        if askokcancel(title="Salir", message="¿Desea salir de la aplicación?", icon=WARNING):
            self.destroy()


app = App().mainloop()


In [2]:
#autor: Cruz Asencios, Cristian Elvis

import tkinter as tk
from PIL import Image, ImageTk
import cv2
from datetime import datetime
from tkinter.messagebox import showinfo
import time

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Status Bar")
        self.geometry("350x150+100+100")

        # El Frame se coloca sobre self.master con pack
        frm = tk.Frame(self)
        frm.pack(padx=10, pady=10)

        self.lblLabel = tk.Label(frm, text="Pasa por aqui...", font="Arial 25 bold", bd=5, relief=tk.GROOVE)
        self.lblLabel.grid(row=0, column=0, padx=25, pady=25)

        # La barra de status va sobre self.master con pack (soporte de side y fill)
        self.statusbar = tk.Label(self, text="Listo…", bd=1, relief=tk.SUNKEN, anchor=tk.W)
        self.statusbar.pack(side=tk.BOTTOM, fill=tk.X)

        # Definicion de eventos con bind asociados al statusbar
        self.lblLabel.bind("<Enter>", lambda x: self.update_statusbar("Estoy por aqui..."))
        self.lblLabel.bind("<Leave>", lambda x: self.update_statusbar("Ya no estoy por aqui"))

    def update_statusbar(self, message):
        self.statusbar.config(text=message)


app = App().mainloop()

In [4]:
class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Menu")
        self.geometry("300x300+100+100")

        frm = tk.Frame(self)
        frm.pack(padx=10, pady=10)

        # Se define el menu principal y se le asigna el widget a la centana self.master
        main_menu = tk.Menu(self)
        self.config(menu=main_menu)

        # Se definen los menus (submenus) del menu principal
        menu_archivo = tk.Menu(main_menu, tearoff=False)
        menu_acerca_de = tk.Menu(main_menu, tearoff=False)

        # Se define la organizacion de los menus (command, separator, cascade)
        menu_archivo.add_command(label="Abrir")
        menu_archivo.add_separator()
        menu_archivo.add_command(label="Salir", command=self.destroy)

        menu_acerca_de.add_command(label="Acerca de...")

        main_menu.add_cascade(label="Archivo", menu=menu_archivo)
        main_menu.add_cascade(label="Ayuda", menu=menu_acerca_de)


app = App().mainloop()

In [ ]:
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.scrolledtext import ScrolledText
import serial
import serial.tools.list_ports
from PIL import Image,ImageTk
from datetime import datetime
import threading
from tkinter import filedialog as fd
from tkinter.messagebox import showinfo, WARNING,ERROR


class SerialChat:
    def __init__(self, master):
        self.master = master
        self.PORT = "COM1"

        self.master.title(f"Serial Chat")
        self.master.geometry("+50+50")
        self.master.resizable(0, 0)
        self.master.config(background="#424242")
        #-----------------------ICONOS---------------------------------
        self.send_icon = Image.open('send_icon_144140.ico')
        self.send_icon = ImageTk.PhotoImage(self.send_icon)

        self.state_icon = Image.open('verde.png')
        self.state_icon  = self.state_icon .resize((10, 10))
        self.state_icon = ImageTk.PhotoImage(self.state_icon)

        self.state_icon2 = Image.open('rojo.png')
        self.state_icon2 = self.state_icon2.resize((10, 10))
        self.state_icon2 = ImageTk.PhotoImage(self.state_icon2)

        self.port_icon= Image.open('puertoimg.png')
        self.port_icon = self.port_icon.resize((20, 20))
        self.port_icon= ImageTk.PhotoImage(self.port_icon)

        self.user_icon = Image.open('user.png')
        self.user_icon = self.user_icon.resize((20, 20))
        self.user_icon = ImageTk.PhotoImage(self.user_icon)

        #----------------------STYLOS---------------------------------
        self.s = ttk.Style()
        self.s.configure(
            "MyEntry.TEntry",
            background="#64dd17",
            foreground="#64dd17",
        )
        self.conectar=True

        self.message_data = tk.StringVar()
        self.message_data.set("")

        self.user_name= tk.StringVar()
        self.user_name.set("")



        # ---------------------- SERIAL PORT --------------------------
        self.serial = None
        ## -----------------------PORT LIST ----------------------------
        self.ports=serial.tools.list_ports.comports()
        self.list_ports=[]
        for port in self.ports:
            coms = str(port).split()[0]
            self.list_ports.append(coms)
        #-------------------------LIST EMOTICONS------------------------
        self.list_emojis = ["\U0001F600", "\U0001F603","\U0001F604", "\U0001F601",
                            "\U0001F606", "\U0001F605","\U0001F923", "\U0001F602",
                            "\U0001F642", "\U0001F643","\U0001F609","\U0001F60A",
                            "\U0001F607","\U0001F970", "\U0001F60D","\U0001F929",
                            "\U0001F618","\U0001F972", "\U0001F60B","\U0001F61C",
                            "\U0001F92A", "\U0001F917","\U0001F92B", "\U0001F60F",
                            "\U0001F924","\U0001F637","\U0001F92E", "\U0001F975",
                            "\U0001F60E","\U0001F632","\U0001F631", "\U0001F62B",
                            "\U0001F621","\U0001F921","\U0001F49A","\U0001F499",
                            "\U0001F44B"]
        #-------------------------MENU --------------------------------
        self.main_menu = tk.Menu(self.master)
        self.master.config(menu=self.main_menu)

        self.menu_archivo = tk.Menu(self.main_menu, tearoff=False)
        self.menu_acerca_de = tk.Menu(self.main_menu, tearoff=False)
        self.menu_archivo.add_command(label="Guardar conversación", command=self.save)
        self.menu_archivo.add_separator()
        self.menu_archivo.add_command(label="Salir", command=self.cerrar_puertos)

        self.menu_acerca_de.add_command(label="Acerca de...")

        self.main_menu.add_cascade(label="Archivo", menu=self.menu_archivo)
        self.main_menu.add_cascade(label="Ayuda", menu=self.menu_acerca_de)
        # ------------------------ FRAMES -----------------------------
        frm1 = tk.LabelFrame(self.master, text="Conexión",foreground="white")
        frm2 = tk.Frame(self.master)
        frm3 = tk.LabelFrame(self.master, text="Enviar mensaje",foreground="white")
        frm1.config(background="#424242")
        frm2.config(background="#424242")
        frm3.config(background="#424242")
        frm1.pack(padx=5, pady=5, fill='x')
        frm2.pack(padx=5, pady=5, fill="y", expand=True)
        frm3.pack(padx=5, pady=5,fill='x')

        # ------------------------ FRAME 1 ----------------------------
        self.lblCOM = tk.Label(frm1, text="Puerto COM:",background="#424242",foreground="white",width=100,image=self.port_icon,
                                 compound=tk.LEFT)
        self.lblUser = tk.Label(frm1, text="Username: ", background="#424242", foreground="white",width=100,image=self.user_icon,
                                 compound=tk.LEFT)
        self.cboPort = ttk.Combobox(frm1, values=self.list_ports)#Importante     @@@@@@@@@@@
        self.lblSpace = tk.Label(frm1, text="Offline ",width=80,image=self.state_icon2,
                                 compound=tk.RIGHT, background="#424242",foreground="white" )#importante
        self.btnConnect = tk.Button(frm1, text="Conectar", width=10, command=self.connection, background="#64dd17")#importante
        self.inUser=tk.Entry(frm1, width=23,textvariable=self.user_name)
        self.lblCOM.grid(row=0, column=0, padx=5, pady=5)
        self.lblUser.grid(row=1, column=0, padx=5, pady=5)
        self.inUser.grid(row=1, column=1, padx=5, pady=5,sticky=tk.W)

        self.cboPort.grid(row=0, column=1, padx=5, pady=5)
        self.lblSpace.grid(row=0, column=2, padx=30, pady=5)
        self.btnConnect.grid(row=0, column=3, padx=5, pady=5)

        # ------------------------ FRAME 2 ---------------------------
        self.txtChat = ScrolledText(frm2, height=10, width=50, wrap=tk.WORD, state='disabled')#importante
        self.txtChat.grid(row=0, column=0, columnspan=3, padx=5, pady=5)

        #self.Font_tuple = ("cursive",12,"bold")
        self.Font_tuple = ("Comic Sans MS", 12, "bold")

        # Parsed the specifications to the.
        # Text widget using configure() method.
        self.txtChat.configure(font=self.Font_tuple)

        # ------------------------ FRAME 3 --------------------------
        self.lblText = tk.Label(frm3, text="Mensaje:",background="#424242",foreground="white")#cambiar por mensaje
        self.inText = tk.Entry(frm3, width=30, state='disabled', textvariable=self.message_data,font=3)#importante
        self.emoticons= ttk.Combobox(frm3, width=3, state="disabled", values=self.list_emojis,font=10, background="blue")
        self.btnSend = tk.Button(frm3, width=30, state='disabled',image=self.send_icon, background="#c5e1a5",command=self.Send)#importante
        self.lblText.grid(row=0, column=0, padx=5, pady=5)
        self.inText.grid(row=0, column=1, padx=5, pady=5, ipady=8)
        self.emoticons.grid(row=0, column=2, padx=5, pady=5, ipady=6)
        self.btnSend.grid(row=0, column=3, padx=5, pady=5)
        self.emoticons.bind("<<ComboboxSelected>>", self.add_emoji)
        #self.inText.bind("<Return>", self.Send)

        # --------------------------- StatusBar -----------------------
        self.statusFrame=tk.Frame(self.master,relief=tk.SUNKEN,background="#64dd17")
        self.statusFrame.pack(side=tk.BOTTOM, fill=tk.X)

        self.statusBar = ttk.Label(self.statusFrame,width=50, text="Seleccionar puerto e insertar nombre de usuario",background="#64dd17")
        self.statusBar.grid(row=0,column=0, padx=10,sticky=tk.W)
        self.statusBar2 = tk.Label(self.statusFrame,background="#64dd17")
        self.statusBar2.grid(row=0,column=1, padx=5, sticky=tk.W)

        # eventos bind
        self.btnSend.bind("<Enter>", lambda x: self.update_statusbar("Enviar mensaje"))
        self.btnSend.bind("<Leave>", lambda x: self.update_statusbar(""))
        self.emoticons.bind("<Enter>", lambda x: self.update_statusbar("Seleccionar sticker"))
        self.emoticons.bind("<Leave>", lambda x: self.update_statusbar(""))
        self.inText.bind("<Enter>", lambda x: self.update_statusbar("Escribir su mensaje"))
        self.inText.bind("<Leave>", lambda x: self.update_statusbar("                          "))

        # eventos bind
        self.cboPort.bind("<Enter>", lambda x: self.update_statusbar("Seleccionar un puerto"))
        self.cboPort.bind("<Leave>", lambda x: self.update_statusbar(""))
        self.inUser.bind("<Enter>", lambda x: self.update_statusbar("Ingrese su nombre de usuario"))
        self.inUser.bind("<Leave>", lambda x: self.update_statusbar(""))
        self.btnConnect.bind("<Enter>", lambda x: self.update_statusbar("Establecer Conexión"))##no olvidar
        self.btnConnect.bind("<Leave>", lambda x: self.update_statusbar(""))

        #self.cboPort.bind("<Leave>", lambda x: self.update_statusbar(""))

        # ------------- Control del boton "X" de la ventana -----------
        self.master.protocol("WM_DELETE_WINDOW", self.cerrar_puertos)
        th1 = threading.Thread(target=self.Receive, daemon=True)
        th1.start()


    def add_emoji(self,event):
        self.inText.insert("end",self.emoticons.get())



    def connection(self):
        self.user = self.user_name.get()
        self.PORT=self.cboPort.get()

        if len(self.PORT)==0:
            showinfo(title="ADVERTENCIA!", message=f"No ha seleccionado un puerto",icon=WARNING)
        elif len(self.user)==0:
            showinfo(title="ADVERTENCIA!", message=f"El campo para el nombre de usuario está vacío.",icon=WARNING)

        else:
            if self.conectar== True:
                try:
                    self.statusBar.config(text=f"Conectado al {self.PORT} a 9600")
                    self.serial = serial.Serial(port=self.PORT,
                                             baudrate=9600,
                                             bytesize=8,
                                             timeout=2,
                                             stopbits=serial.STOPBITS_ONE)
                    self.cboPort.config(state='disabled')
                    self.inUser.config(state='disabled')
                    self.btnConnect.config(text="Desconectar", background="#d50000")
                    self.inText.config(state='normal')
                    self.emoticons.config(state='normal')
                    self.btnSend.config(state='normal',background="#64dd17")
                    self.lblSpace.config(text="Online ",image=self.state_icon,compound=tk.RIGHT)
                    self.conectar = False




                except:
                    showinfo(title="ADVERTENCIA!", message=f"Error al conectarse a {self.PORT}. Intente Seleccionar otro puerto",
                             icon=ERROR)
                    self.statusBar.config(text=f"Seleccionar puerto e insertar nombre de usuario")
                    self.cboPort.config(state='normal')
                    self.inUser.config(state='normal')
                    self.inText.config(state='disabled')
                    self.emoticons.config(state='disabled')
                    self.btnSend.config(state='disabled', background="#c5e1a5")
                    self.btnConnect.config(text="Conectar", background="#64dd17")
                    self.lblSpace.config(text="Offline ",image=self.state_icon2,compound=tk.RIGHT)
                    self.conectar = True
                    self.serial.close()

            else:
                self.cboPort.config(state='normal')
                self.inUser.config(state='normal')
                self.inText.config(state='disabled')
                self.emoticons.config(state='disabled')
                self.btnSend.config(state='disabled', background="#c5e1a5")
                self.btnConnect.config(text="Conectar",background="#64dd17")
                self.lblSpace.config(text="Offline ",image=self.state_icon2,compound=tk.RIGHT)
                self.statusBar.config(text=f"Seleccionar puerto e insertar nombre de usuario")#modificar
                self.conectar = True
                self.serial.close()
    def Send(self):
        User=self.user_name.get()
        message=self.message_data.get()
        self.message_data.set("")
        if len(message)>0:
            time = f"{datetime.now():%H:%M %p}"
            self.txtChat.config(state='normal')
            self.txtChat.insert(tk.INSERT,f'{User}-[{time}]: '+message + '\n', 'azul')

            self.txtChat.config(state='disabled')
            self.txtChat.tag_config('verde', foreground='green')
            self.txtChat.tag_config('negro', foreground='black')
            self.txtChat.tag_config('azul', foreground='blue')

            paquete=User+'%'+message
            data = paquete.encode("UTF-8")
            self.serial.write(data)





    def Receive(self):
        while True:
            #self.conectar==false: Está conectado-no requiere conectar
            #self.conectar==true: Está desconectado- requiere conectar
            if self.conectar == False:
                try:
                    if self.serial.in_waiting > 0:
                        self.statusBar.config(text="Recibiendo mensaje...")

                        paquete = self.serial.readline()
                        data = paquete.decode('UTF-8')
                        User,message=data.split("%")

                        time = f"{datetime.now():%H:%M %p}"
                        self.txtChat.config(state='normal')
                        self.txtChat.insert(tk.INSERT,f'{User}-[{time}]: '+message + '\n', 'color_pick')
                        self.txtChat.tag_config('color_pick', foreground='#ad1457')
                        self.txtChat.config(state='disabled')

                except:
                    break

    def save(self):
        file = fd.asksaveasfilename(initialdir="/", title="Seleccione la carpeta", defaultextension=".txt.",
                                    filetypes=(("txt files", "*.txt"), ("all files", "*.*")))
        imprimir = self.txtChat.get("1.0", tk.END)
        fl = open(file, "w", encoding=("utf-8"))
        fl.write(imprimir)

    def update_statusbar(self, message):
        self.statusBar2.config(text=message)

    def cerrar_puertos(self):
        # Se cierran los puertos COM y la ventana de tkinter
        try:

            self.serial.close()
        except:
            pass

        self.master.destroy()

root = tk.Tk()
app = SerialChat(root)
root.mainloop()